version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"

  task-service:
    build: ./task-service
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASS: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: taskdb
      
