version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8081:80"
    depends_on:
      - task-service


  task-service:
    build: ./task-service
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASS: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: taskdb
  tester:
    image: golang:1.21
    volumes:
      - .:/app
    working_dir: /app/task-service
    depends_on:
      - mysql
    environment:
      DB_USER: root
      DB_PASS: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: taskdb
    command: ["go", "test", "./tests", "-v"]

      
